In [1]:
import pandas as pd
import numpy as np
from linear_regression import *

In [2]:
gss = pd.read_csv('../Datasets/gss.csv', low_memory=False) 
gss_2010 = gss.loc[gss["yrint"] == 2010].dropna(subset=['paeduc', 'maeduc', 'age', 'educ'])
X, y = gss_2010[['paeduc', 'maeduc', 'age']], gss_2010['educ']

In [ ]:
X_numpy = np.hstack([np.ones((np.asarray(X, dtype=float).shape[0], 1)), np.asarray(X, dtype=float)])
y_numpy = np.asarray(y, dtype=float)
np_model = LinearRegressionOLS().fit(X_numpy, y_numpy, feature_names=['const', 'paeduc','maeduc','age'], target_name="Education")

print(X_numpy, y_numpy)
print(np_model)

[[ 1.  8.  3. 31.]
 [ 1. 18.  6. 23.]
 [ 1.  2.  0. 82.]
 ...
 [ 1. 12. 14. 54.]
 [ 1.  6. 12. 57.]
 [ 1. 12. 12. 30.]] [16. 16. 10. ... 12. 16. 14.]

OLS Regression Results
Dependent:                Education
-----------------------------------
 
const                     7.3256***
                           (0.3684)
 
paeduc                    0.2144***
                           (0.0241)
 
maeduc                    0.2569***
                           (0.0271)
 
age                       0.0241***
                           (0.0043)

-----------------------------------
R-squared                     0.276
Adjusted R-squared            0.274
F Statistic                 177.548
Observations               1402.000
Log Likelihood            -3359.107
AIC                        6726.213
BIC                        6747.196
*p<0.1; **p<0.05; ***p<0.01



In [ ]:
X_const = X.copy()
X_const.insert(0, 'const', np.ones(len(X)))
model = LinearRegressionOLS().fit(X_const, y)

print(model)


OLS Regression Results
Dependent:                     educ
-----------------------------------
 
const                     7.3256***
                           (0.3684)
 
paeduc                    0.2144***
                           (0.0241)
 
maeduc                    0.2569***
                           (0.0271)
 
age                       0.0241***
                           (0.0043)

-----------------------------------
R-squared                     0.276
Adjusted R-squared            0.274
F Statistic                 177.548
Observations               1402.000
Log Likelihood            -3359.107
AIC                        6726.213
BIC                        6747.196
*p<0.1; **p<0.05; ***p<0.01



In [5]:
print(RegressionOutput([model, np_model], 15, 20))


OLS Regression Results
Dependent:                     educ      Education
--------------------------------------------------
 
const                     7.3256***      7.3256***
                           (0.3684)       (0.3684)
 
paeduc                    0.2144***      0.2144***
                           (0.0241)       (0.0241)
 
maeduc                    0.2569***      0.2569***
                           (0.0271)       (0.0271)
 
age                       0.0241***      0.0241***
                           (0.0043)       (0.0043)

--------------------------------------------------
R-squared                     0.276          0.276
Adjusted R-squared            0.274          0.274
F Statistic                 177.548        177.548
Observations               1402.000       1402.000
Log Likelihood            -3359.107      -3359.107
AIC                        6726.213       6726.213
BIC                        6747.196       6747.196
*p<0.1; **p<0.05; ***p<0.01



In [6]:
pd.DataFrame(model.feature_summary())

feature  coefficient      se  t_statistic p_>_abs_t conf_interval__0.05
0   const       7.3256  0.3684      19.8870     0.000      [6.603, 8.048]
1  paeduc       0.2144  0.0241       8.8796     0.000      [0.167, 0.262]
2  maeduc       0.2569  0.0271       9.4725     0.000       [0.204, 0.31]
3     age       0.0241  0.0043       5.5789     0.000      [0.016, 0.033]

In [7]:
pd.DataFrame(model.VarianceInflationFactor())

feature     VIF
0  paeduc  2.0233
1  maeduc  2.0285
2     age  1.0971

In [8]:
pd.DataFrame(model.RobustStandardError(type="HC3"))

feature  robust_se   robust_t      robust_p
0   const   0.434460  16.861504  0.000000e+00
1  paeduc   0.023602   9.084741  0.000000e+00
2  maeduc   0.029439   8.727734  0.000000e+00
3     age   0.004221   5.715290  1.336690e-08

In [9]:
model.predict(np.array([[0, 0, 0], ]))

array([7.32564767])

In [10]:
prediction_set = [
    np.array([[0, 0, 0], ]),
    np.array([[X['paeduc'].mean(), X['maeduc'].mean(), X['age'].mean(),], ]),
    np.array([[X['paeduc'].mean(), 14,  X['age'].mean()], ]),
    np.array([[11.624822, 11.659058, 48.225392], ]),
    np.array([[8, 14,  X['age'].mean()], ]),
] 
predictions = pd.concat([pd.DataFrame(model.predict(test_set, return_table=True)) for test_set in prediction_set], ignore_index=True)
predictions

features  prediction  std_error  \
0  {'paeduc': '0.00', 'maeduc': '0.00', 'age': '0...      7.3256     0.3684   
1  {'paeduc': '11.62', 'maeduc': '11.66', 'age': ...     13.9772     0.0710   
2  {'paeduc': '11.62', 'maeduc': '14.00', 'age': ...     14.5786     0.0953   
3  {'paeduc': '11.62', 'maeduc': '11.66', 'age': ...     13.9772     0.0710   
4  {'paeduc': '8.00', 'maeduc': '14.00', 'age': '...     13.8014     0.1560   

   t_statistic  P>|t|  ci_low_0.05  ci_high_0.05  
0      19.8870    0.0       6.6030        8.0483  
1     196.7284    0.0      13.8378       14.1165  
2     152.9974    0.0      14.3917       14.7656  
3     196.7284    0.0      13.8378       14.1165  
4      88.4816    0.0      13.4954       14.1074

In [11]:
prediction_set = [
    (np.array([[i, X['maeduc'].mean(), X['age'].mean()],]))
    for i in range(int(X['paeduc'].min()), int(X['paeduc'].max())+1)
    ] 
predictions = pd.concat([pd.DataFrame(model.predict(i, return_table=True)) for i in prediction_set], ignore_index=True)
predictions

features  prediction  std_error  \
0   {'paeduc': '0.00', 'maeduc': '11.66', 'age': '...     11.4846     0.2896   
1   {'paeduc': '1.00', 'maeduc': '11.66', 'age': '...     11.6990     0.2662   
2   {'paeduc': '2.00', 'maeduc': '11.66', 'age': '...     11.9134     0.2430   
3   {'paeduc': '3.00', 'maeduc': '11.66', 'age': '...     12.1278     0.2201   
4   {'paeduc': '4.00', 'maeduc': '11.66', 'age': '...     12.3423     0.1974   
5   {'paeduc': '5.00', 'maeduc': '11.66', 'age': '...     12.5567     0.1750   
6   {'paeduc': '6.00', 'maeduc': '11.66', 'age': '...     12.7711     0.1533   
7   {'paeduc': '7.00', 'maeduc': '11.66', 'age': '...     12.9855     0.1324   
8   {'paeduc': '8.00', 'maeduc': '11.66', 'age': '...     13.1999     0.1127   
9   {'paeduc': '9.00', 'maeduc': '11.66', 'age': '...     13.4144     0.0952   
10  {'paeduc': '10.00', 'maeduc': '11.66', 'age': ...     13.6288     0.0812   
11  {'paeduc': '11.00', 'maeduc': '11.66', 'age': ...     13.8432     0.0726   
12  {'paeduc': '12.00', 'maeduc': '11.66', 'age': ...     14.0576     0.0716   
13  {'paeduc': '13.00', 'maeduc': '11.66', 'age': ...     14.2720     0.0784   
14  {'paeduc': '14.00', 'maeduc': '11.66', 'age': ...     14.4865     0.0913   
15  {'paeduc': '15.00', 'maeduc': '11.66', 'age': ...     14.7009     0.1081   
16  {'paeduc': '16.00', 'maeduc': '11.66', 'age': ...     14.9153     0.1273   
17  {'paeduc': '17.00', 'maeduc': '11.66', 'age': ...     15.1297     0.1480   
18  {'paeduc': '18.00', 'maeduc': '11.66', 'age': ...     15.3441     0.1695   
19  {'paeduc': '19.00', 'maeduc': '11.66', 'age': ...     15.5586     0.1917   
20  {'paeduc': '20.00', 'maeduc': '11.66', 'age': ...     15.7730     0.2144   

    t_statistic  P>|t|  ci_low_0.05  ci_high_0.05  
0       39.6620    0.0      10.9166       12.0526  
1       43.9452    0.0      11.1768       12.2212  
2       49.0201    0.0      11.4367       12.3902  
3       55.1134    0.0      11.6962       12.5595  
4       62.5393    0.0      11.9551       12.7294  
5       71.7361    0.0      12.2133       12.9001  
6       83.3162    0.0      12.4704       13.0718  
7       98.1061    0.0      12.7259       13.2452  
8      117.0875    0.0      12.9788       13.4211  
9      140.8904    0.0      13.2276       13.6011  
10     167.9212    0.0      13.4696       13.7880  
11     190.5925    0.0      13.7007       13.9857  
12     196.2714    0.0      13.9171       14.1981  
13     181.9825    0.0      14.1182       14.4259  
14     158.6529    0.0      14.3073       14.6656  
15     135.9656    0.0      14.4888       14.9130  
16     117.1510    0.0      14.6655       15.1651  
17     102.2488    0.0      14.8395       15.4200  
18      90.5001    0.0      15.0115       15.6767  
19      81.1438    0.0      15.1824       15.9347  
20      73.5832    0.0      15.3525       16.1935

In [12]:
# Do not include the intercept
results = model.HypothesisTesting(test=np.array([[0, 0, 0], ]), hyp=np.array([[1, 1, 1], ]))
print(results['summary'])
pd.DataFrame(results['table']).T

Significance Analysis (p > |t|)
1.96 > |-1.3451| == True

Fail to reject the null hypothesis: 7.3256 is not statistically different from 7.8211 at 5.0% level

Conclude that outcome of {'paeduc': '0.00', 'maeduc': '0.00', 'age': '0.00'}
does not differ from {'paeduc': '1.00', 'maeduc': '1.00', 'age': '1.00'}


0
feature_labels     {'paeduc': '0.00', 'maeduc': '0.00', 'age': '0...
hypothesis_labels  {'paeduc': '1.00', 'maeduc': '1.00', 'age': '1...
prediction                                                  7.325648
hypothesis                                                  7.821124
t-statistic                                                -1.345073
P>|t|                                                        0.17882

In [13]:
# Hypothesis testing with one array and a fixed value
results = model.HypothesisTesting(test=np.array([[0, 0, 0], ]), hyp=7.325648)
print(results['summary'])
pd.DataFrame(results['table']).T

Significance Analysis (p > |t|)
1.96 > |-0.0000| == True

Fail to reject the null hypothesis: 7.3256 is not statistically different from 7.3256 at 5.0% level

Conclude that outcome of {'paeduc': '0.00', 'maeduc': '0.00', 'age': '0.00'}
does not differ from {'educ': '7.325648'}


0
feature_labels     {'paeduc': '0.00', 'maeduc': '0.00', 'age': '0...
hypothesis_labels                               {'educ': '7.325648'}
prediction                                                  7.325648
hypothesis                                                  7.325648
t-statistic                                                -0.000001
P>|t|                                                       0.999999